### ISSUE TITLE
urgent : Finished competition link inactive

### ISSUE THREAD

**Issue by arungsZoo** [dilawar/HippoApp#52]
Hi Dilawar,  
 We have marked the judges' voting as ended. So the competition is now a Finished competition.
But presently not able to view entries
@dilawar 
@photography2018

**Comment by arungsZoo** [comment]
Currently I have reverted the status back to the previous mode, since  people will be coming to see the winning entries  (also rest of them)

**Comment by arungsZoo** [comment]
When the judging phase is done, can we show the following information also in full screen mode?
1. Uploader's name  (Perhaps at left side of the Close icon on top right)
2. Number of votes and average votes (not important at the moment)

**Comment by dilawar** [comment]
Fixed by https://github.com/dilawar/HippoApp/commit/32904f35ee308230ab3f03a2de9c0b1af93436eb

**Comment by arungsZoo** [comment]
The interface looks great now.
@dilawar  The hippo app is still not showing the photos
